Add HA standard wind speed sensor device default config value (TZ-1214)
espressif/esp-zigbee-sdk pull request #451
Opened 2024-10-13 13:21 UTC by lboue

## Description
Add HA standard wind speed sensor device default config value
Add Zigbee HA standard wind speed sensor clusters

## Related
[Zigbee Wind speed sensor example #10455](https://github.com/espressif/arduino-esp32/pull/10455)

## Testing

---

## Checklist

Before submitting a Pull Request, please ensure the following:

- [X] 🚨 This PR does not introduce breaking changes.
- [X] All CI checks (GH Actions) pass.
- [x] Documentation is updated as needed.
- [x] Tests are updated or added as necessary.
- [x] Code is well-commented, especially in complex areas.
- [x] Git history is clean — commits are squashed to the minimum necessary.

2024-10-24 07:28 UTC, P-R-O-C-H-Y requested changes
@lboue PTAL

2024-10-27 11:20 UTC, lboue commented
Thanks @P-R-O-C-H-Y. I applied requested changes. Is it OK now?

2024-10-28 08:27 UTC, xieqinan commented
Hi @lboue,

It appears that the wind speed sensor does not align with the standard HA devices defined by the Zigbee Home Automation Profile. Could you please provide more details for reference?

2024-10-29 05:55 UTC, P-R-O-C-H-Y approved these changes

2024-10-31 03:44 UTC, xieqinan commented
@lboue ，

The Wind Speed Measurement cluster is a standard cluster defined by the ZCL specification, but it’s not a standard device type within the Zigbee Home Automation Public Application Profile. I suggest defining this structure within your project first.

2025-03-17 16:27 UTC, closed without merging